[package]
name = "snake_q"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.10"
# rand = "0.8.4"
# getrandom = { version = "0.2.3", features = ["js"] }
